name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Create Release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore WakFocus/WakFocus.csproj

    - name: Build Release (Framework-dependent)
      run: dotnet publish WakFocus/WakFocus.csproj -c Release -o ./publish/framework-dependent

    - name: Build Release (Self-contained)
      run: dotnet publish WakFocus/WakFocus.csproj -c Release -r win-x64 --self-contained -o ./publish/self-contained

    - name: Generate checksums
      shell: pwsh
      run: |
        $frameworkExe = "./publish/framework-dependent/WakFocus.exe"
        $selfContainedExe = "./publish/self-contained/WakFocus.exe"

        $frameworkHash = (Get-FileHash -Path $frameworkExe -Algorithm SHA256).Hash
        $selfContainedHash = (Get-FileHash -Path $selfContainedExe -Algorithm SHA256).Hash

        @"
        # SHA256 Checksums

        ## WakFocus.exe (Framework-dependent)
        ``````
        $frameworkHash
        ``````

        ## WakFocus.exe (Self-contained)
        ``````
        $selfContainedHash
        ``````

        ## How to verify
        On Windows PowerShell:
        ``````powershell
        Get-FileHash -Path WakFocus.exe -Algorithm SHA256
        ``````
        "@ | Out-File -FilePath checksums.txt -Encoding UTF8

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./publish/framework-dependent/WakFocus.exe
          ./publish/self-contained/WakFocus.exe
          checksums.txt
        body: |
          ## Downloads

          - **WakFocus.exe** (Framework-dependent) - Requires .NET 8.0 Runtime
          - **WakFocus.exe** (Self-contained) - No runtime required, larger file size

          ## Security

          - ✅ Built automatically by GitHub Actions
          - ✅ SHA256 checksums provided (see checksums.txt)
          - ✅ Source code scanned with CodeQL
          - 🔒 VirusTotal scan results will be posted shortly

          ## Verification

          Download `checksums.txt` and verify the SHA256 hash matches your downloaded executable.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
