name: VirusTotal Scan

on:
  release:
    types: [published]

jobs:
  scan:
    name: Scan Release with VirusTotal
    runs-on: ubuntu-latest

    steps:
    - name: Download release assets
      uses: robinraju/release-downloader@v1.8
      with:
        latest: true
        fileName: "*.exe"
        out-file-path: "downloads"

    - name: Scan with VirusTotal
      uses: crazy-max/ghaction-virustotal@v4
      with:
        vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
        files: |
          downloads/*.exe

    - name: Comment scan results on release
      uses: actions/github-script@v7
      with:
        script: |
          const release = context.payload.release;
          const comment = `## 🛡️ VirusTotal Security Scan

          All release executables have been scanned with VirusTotal (70+ antivirus engines).

          ✅ Scan completed successfully. Check the Actions tab for detailed results.

          **Note:** False positives are common for new executables. If you see any detections, they're likely generic heuristic warnings, not actual malware.`;

          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: release.number,
            body: comment
          });
